language: scala

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - travis_retry sbt ++$TRAVIS_SCALA_VERSION coverage test it:test scalastyle && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
